version: 2
updates:
  # ✅ Monitor Node.js dependencies (package.json)
  - package-ecosystem: "npm"
    directory: "/" # Root directory
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(npm):"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "lodash"
        versions: ["<4.17.21"]

  # ✅ Monitor Python dependencies (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(pip):"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "requests"
        versions: [">=3.0.0"]

  # ✅ Monitor Docker image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker):"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      - dependency-name: "node"
        versions: ["<16"]

  # ✅ Monitor GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(actions):"
      include: "scope"
    labels:
      - "dependencies"
      - "ci/cd"
    open-pull-requests-limit: 3

  # ✅ Security updates (Prioritize security patches)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "security"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "express"
        versions: ["<5.0.0"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "security"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "flask"
        versions: [">=3.0.0"]
