version: 2
updates:
  # ✅ Monitor Node.js dependencies (package.json)
  - package-ecosystem: "npm"
    directory: "/" # Root directory
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(npm):"
      include: "scope"

  # ✅ Monitor Python dependencies (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(pip):"
      include: "scope"

  # ✅ Monitor Docker image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker):"
      include: "scope"

  # ✅ Monitor GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(actions):"
      include: "scope"
